OnEnable: "Command Logger Plugin has been started!"
OnDisable: "Command Logger Plugin was stopped"

BotSettings:
  botToken: ""
  botID: ""
  chatID: ""

SendLog: "Player %s ran command %s at world %s (x: %.1f, y: %.1f, z: %.1f)"

LogCommands:
  - "/ban"
  - "/tp"
  - "/time"